window.players = [
  {
    "name": "Lionel Messi",
    "clubs": ["Barcelona", "PSG", "Inter Miami"],
    "leagues": ["La Liga", "Ligue 1", "MLS"],
    "nationality": "Argentina",
    "positions": ["RW", "ST", "CAM"],
    "YearOfBirth": 1987,
    "strongFoot": "Left",
    "status": "Current",
     "image": "./images/players/lionel_messi.jpg"
 },
  {
    "name": "Cristiano Ronaldo",
    "clubs": ["Sporting CP", "Manchester United", "Real Madrid", "Juventus", "Al Nassr"],
    "leagues": ["Primeira Liga", "Premier League", "La Liga", "Serie A", "Saudi Pro League"],
    "nationality": "Portugal",
    "positions": ["ST", "LW"],
    "YearOfBirth": 1985,
    "strongFoot": "Right",
    "status": "Current",
    "image": "./images/players/cristiano_ronaldo.jpg"
  },
  {
    "name": "Neymar",
    "clubs": ["Santos", "Barcelona", "PSG", "Al Hilal"],
    "leagues": ["Brasileirao", "La Liga", "Ligue 1", "Saudi Pro League"],
    "nationality": "Brazil",
    "positions": ["LW", "CAM"],
    "YearOfBirth": 1992,
    "strongFoot": "Right",
    "status": "Current",
    "image": "./images/players/neymar.jpg"
  },
  {
    "name": "Kylian Mbappe",
    "clubs": ["Monaco", "PSG", "Real Madrid"],
    "leagues": ["Ligue 1", "La Liga"],
    "nationality": "France",
    "positions": ["LW", "ST"],
    "YearOfBirth": 1998,
    "strongFoot": "Right",
    "status": "Current",
    "image": "./images/players/mbappe.jpg"
  },
  {
    "name": "Erling Haaland",
    "clubs": ["Bryne", "Molde", "RB Salzburg", "Borussia Dortmund", "Manchester City"],
    "leagues": ["Eliteserien", "Austrian Bundesliga", "Bundesliga", "Premier League"],
    "nationality": "Norway",
    "positions": ["ST"],
    "YearOfBirth": 2000,
    "strongFoot": "Left",
    "status": "Current",
    "image": "./images/players/haaland.jpg"
  },
  {
    "name": "Zinedine Zidane",
    "clubs": ["Cannes", "Bordeaux", "Juventus", "Real Madrid"],
    "leagues": ["Ligue 1", "Serie A", "La Liga"],
    "nationality": "France",
    "positions": ["CAM", "CM"],
    "YearOfBirth": 1972,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "./images/players/zidane.jpg"
  },
  {
    "name": "Ronaldinho",
    "clubs": ["Gremio", "PSG", "Barcelona", "AC Milan", "Flamengo", "Atletico Mineiro", "Queretaro", "Fluminense"],
    "leagues": ["Brasileirao", "Ligue 1", "La Liga", "Serie A", "Liga MX"],
    "nationality": "Brazil",
    "positions": ["CAM", "LW"],
    "YearOfBirth": 1980,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/04/Ronaldinho_2019.jpg"
  },
  {
    "name": "Thierry Henry",
    "clubs": ["Monaco", "Juventus", "Arsenal", "Barcelona", "New York Red Bulls"],
    "leagues": ["Ligue 1", "Serie A", "Premier League", "La Liga", "MLS"],
    "nationality": "France",
    "positions": ["ST", "LW"],
    "YearOfBirth": 1977,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/1c/Thierry_Henry_2012.jpg"
  },
  {
    "name": "David Beckham",
    "clubs": ["Manchester United", "Preston North End (loan)", "Real Madrid", "LA Galaxy", "AC Milan (loan)", "PSG"],
    "leagues": ["Premier League", "English League One", "La Liga", "MLS", "Serie A", "Ligue 1"],
    "nationality": "England",
    "positions": ["RM", "CM"],
    "YearOfBirth": 1975,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0c/David_Beckham_2019.jpg"
  },
  {
    "name": "Andres Iniesta",
    "clubs": ["Barcelona", "Vissel Kobe", "Emirates Club"],
    "leagues": ["La Liga", "J1 League", "UAE Pro League"],
    "nationality": "Spain",
    "positions": ["CM", "CAM"],
    "YearOfBirth": 1984,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/1f/Andr%C3%A9s_Iniesta_2018.jpg"
  },
  {
    "name": "Xavi Hernandez",
    "clubs": ["Barcelona", "Al Sadd"],
    "leagues": ["La Liga", "Qatar Stars League"],
    "nationality": "Spain",
    "positions": ["CM", "CDM"],
    "YearOfBirth": 1980,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Xavi_Hern%C3%A1ndez_2018.jpg"
  },
  {
    "name": "Luka Modric",
    "clubs": ["Dinamo Zagreb", "Zrinjski (loan)", "NK Inter Zapresic (loan)", "Tottenham Hotspur", "Real Madrid", "AC Milan"],
    "leagues": ["HNL", "Premier Liga BiH", "Premier League", "La Liga", "Serie A"],
    "nationality": "Croatia",
    "positions": ["CM", "CDM", "CAM"],
    "YearOfBirth": 1985,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8c/Luka_Modric_2018.jpg"
  },
  {
    "name": "Karim Benzema",
    "clubs": ["Lyon", "Real Madrid", "Al Ittihad", "Al Hilal"],
    "leagues": ["Ligue 1", "La Liga", "Saudi Pro League"],
    "nationality": "France",
    "positions": ["ST", "CF"],
    "YearOfBirth": 1987,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/9c/Karim_Benzema_2022.jpg"
  },
  {
    "name": "Robert Lewandowski",
    "clubs": ["Delta Warsaw", "Znicz Pruszkow", "Lech Poznan", "Borussia Dortmund", "Bayern Munich", "Barcelona"],
    "leagues": ["Ekstraklasa", "Bundesliga", "La Liga"],
    "nationality": "Poland",
    "positions": ["ST"],
    "YearOfBirth": 1988,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Robert_Lewandowski_2020.jpg"
  },
  {
    "name": "Luis Suarez",
    "clubs": ["Nacional", "Groningen", "Ajax", "Liverpool", "Barcelona", "Atletico Madrid", "Gremio", "Inter Miami"],
    "leagues": ["Liga AUF Uruguaya", "Eredivisie", "Premier League", "La Liga", "Brasileirao", "MLS"],
    "nationality": "Uruguay",
    "positions": ["ST"],
    "YearOfBirth": 1987,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Luis_Su%C3%A1rez_2018.jpg"
  },
  {
    "name": "Sergio Ramos",
    "clubs": ["Sevilla", "Real Madrid", "PSG", "Monterrey"],
    "leagues": ["La Liga", "Ligue 1", "Liga MX"],
    "nationality": "Spain",
    "positions": ["CB", "RB"],
    "YearOfBirth": 1986,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Sergio_Ramos_2017.jpg"
  },
  {
    "name": "Gerard Pique",
    "clubs": ["Manchester United", "Real Zaragoza (loan)", "Barcelona"],
    "leagues": ["Premier League", "La Liga"],
    "nationality": "Spain",
    "positions": ["CB"],
    "YearOfBirth": 1987,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Gerard_Piqu%C3%A9_2018.jpg"
  },
  {
    "name": "Iker Casillas",
    "clubs": ["Real Madrid", "Porto"],
    "leagues": ["La Liga", "Primeira Liga"],
    "nationality": "Spain",
    "positions": ["GK"],
    "YearOfBirth": 1981,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Iker_Casillas_2018.jpg"
  },
  {
    "name": "Gianluigi Buffon",
    "clubs": ["Parma", "Juventus", "PSG"],
    "leagues": ["Serie A", "Ligue 1"],
    "nationality": "Italy",
    "positions": ["GK"],
    "YearOfBirth": 1978,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Gianluigi_Buffon_2018.jpg"
  },
  {
    "name": "Manuel Neuer",
    "clubs": ["Schalke", "Bayern Munich"],
    "leagues": ["Bundesliga"],
    "nationality": "Germany",
    "positions": ["GK"],
    "YearOfBirth": 1986,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/6/6e/Manuel_Neuer_2018.jpg"
  },
  {
    "name": "Virgil van Dijk",
    "clubs": ["Groningen", "Celtic", "Southampton", "Liverpool"],
    "leagues": ["Eredivisie", "Scottish Premiership", "Premier League"],
    "nationality": "Netherlands",
    "positions": ["CB"],
    "YearOfBirth": 1991,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Virgil_van_Dijk_2018.jpg"
  },
  {
    "name": "Mohamed Salah",
    "clubs": ["El Mokawloon", "Basel", "Chelsea", "Fiorentina (loan)", "Roma", "Liverpool"],
    "leagues": ["Egyptian Premier League", "Swiss Super League", "Premier League", "Serie A"],
    "nationality": "Egypt",
    "positions": ["RW", "ST"],
    "YearOfBirth": 1992,
    "strongFoot": "Left",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/2e/Mohamed_Salah_2018.jpg"
  },
  {
    "name": "Sadio Mane",
    "clubs": ["Metz", "Red Bull Salzburg", "Southampton", "Liverpool", "Bayern Munich", "Al Nassr"],
    "leagues": ["Ligue 2", "Austrian Bundesliga", "Premier League", "Bundesliga", "Saudi Pro League"],
    "nationality": "Senegal",
    "positions": ["LW", "ST"],
    "YearOfBirth": 1992,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Sadio_Man%C3%A9_2018.jpg"
  },
  {
    "name": "Kevin De Bruyne",
    "clubs": ["Genk", "Chelsea", "Werder Bremen (loan)", "Wolfsburg", "Manchester City", "Napoli"],
    "leagues": ["Belgian Pro League", "Premier League", "Bundesliga", "Serie A"],
    "nationality": "Belgium",
    "positions": ["CAM", "CM"],
    "YearOfBirth": 1991,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Kevin_De_Bruyne_2018.jpg"
  },
  {
    "name": "Eden Hazard",
    "clubs": ["Lille", "Chelsea", "Real Madrid"],
    "leagues": ["Ligue 1", "Premier League", "La Liga"],
    "nationality": "Belgium",
    "positions": ["LW", "CAM"],
    "YearOfBirth": 1991,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8c/Eden_Hazard_2018.jpg"
  },
  {
    "name": "Gareth Bale",
    "clubs": ["Southampton", "Tottenham Hotspur", "Real Madrid", "LAFC"],
    "leagues": ["Premier League", "La Liga", "MLS"],
    "nationality": "Wales",
    "positions": ["RW", "ST"],
    "YearOfBirth": 1989,
    "strongFoot": "Left",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Gareth_Bale_2018.jpg"
  },
  {
    "name": "Didier Drogba",
    "clubs": ["Le Mans", "Guingamp", "Marseille", "Chelsea", "Shanghai Shenhua", "Galatasaray", "Montreal Impact", "Phoenix Rising"],
    "leagues": ["Ligue 1", "Premier League", "Chinese Super League", "Turkish Super Lig", "MLS"],
    "nationality": "Ivory Coast",
    "positions": ["ST"],
    "YearOfBirth": 1978,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Didier_Drogba_2015.jpg"
  },
  {
    "name": "Frank Lampard",
    "clubs": ["West Ham", "Swansea City (loan)", "Chelsea", "Manchester City", "New York City FC"],
    "leagues": ["Premier League", "Championship", "MLS"],
    "nationality": "England",
    "positions": ["CM", "CAM"],
    "YearOfBirth": 1978,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5d/Frank_Lampard_2015.jpg"
  },
  {
    "name": "Steven Gerrard",
    "clubs": ["Liverpool", "LA Galaxy"],
    "leagues": ["Premier League", "MLS"],
    "nationality": "England",
    "positions": ["CM", "CDM"],
    "YearOfBirth": 1980,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Steven_Gerrard_2018.jpg"
  },
  {
    "name": "Paul Scholes",
    "clubs": ["Manchester United"],
    "leagues": ["Premier League"],
    "nationality": "England",
    "positions": ["CM", "CAM"],
    "YearOfBirth": 1974,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Paul_Scholes_2017.jpg"
  },
  {
    "name": "Xabi Alonso",
    "clubs": ["Real Sociedad", "Eibar (loan)", "Liverpool", "Real Madrid", "Bayern Munich"],
    "leagues": ["La Liga", "Segunda División", "Premier League", "Bundesliga"],
    "nationality": "Spain",
    "positions": ["CM", "CDM"],
    "YearOfBirth": 1981,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Xabi_Alonso_2017.jpg"
  },
  {
    "name": "Andriy Shevchenko",
    "clubs": ["Dynamo Kyiv", "AC Milan", "Chelsea", "Dynamo Kyiv"],
    "leagues": ["Ukrainian Premier League", "Serie A", "Premier League"],
    "nationality": "Ukraine",
    "positions": ["ST"],
    "YearOfBirth": 1976,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Andriy_Shevchenko_2012.jpg"
  },
  {
    "name": "Samuel Eto'o",
    "clubs": ["Real Madrid", "Leganes (loan)", "Espanyol (loan)", "Mallorca", "Barcelona", "Inter Milan", "Anzhi Makhachkala", "Chelsea", "Everton", "Sampdoria", "Antalyaspor", "Konyaspor", "Qatar SC"],
    "leagues": ["La Liga", "Serie A", "Russian Premier League", "Premier League", "Turkish Super Lig", "Qatar Stars League"],
    "nationality": "Cameroon",
    "positions": ["ST", "RW"],
    "YearOfBirth": 1981,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Samuel_Eto%27o_2011.jpg"
  },
  {
    "name": "Carlos Puyol",
    "clubs": ["Barcelona"],
    "leagues": ["La Liga"],
    "nationality": "Spain",
    "positions": ["CB", "RB"],
    "YearOfBirth": 1978,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Carles_Puyol_2011.jpg"
  },
  {
    "name": "Philipp Lahm",
    "clubs": ["Bayern Munich", "Stuttgart (loan)"],
    "leagues": ["Bundesliga"],
    "nationality": "Germany",
    "positions": ["RB", "LB", "CDM"],
    "YearOfBirth": 1983,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Philipp_Lahm_2016.jpg"
  },
  {
    "name": "Arjen Robben",
    "clubs": ["Groningen", "PSV", "Chelsea", "Real Madrid", "Bayern Munich"],
    "leagues": ["Eredivisie", "Premier League", "La Liga", "Bundesliga"],
    "nationality": "Netherlands",
    "positions": ["RW"],
    "YearOfBirth": 1984,
    "strongFoot": "Left",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/1c/Arjen_Robben_2016.jpg"
  },
  {
    "name": "Franck Ribery",
    "clubs": ["Boulogne", "Ales", "Brest", "Metz", "Galatasaray", "Marseille", "Bayern Munich", "Fiorentina", "Salernitana"],
    "leagues": ["Turkish Super Lig", "Ligue 1", "Bundesliga", "Serie A"],
    "nationality": "France",
    "positions": ["LW", "RW"],
    "YearOfBirth": 1983,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Franck_Rib%C3%A9ry_2018.jpg"
  },
  {
    "name": "Kaka",
    "clubs": ["Sao Paulo", "AC Milan", "Real Madrid", "Orlando City"],
    "leagues": ["Brasileirao", "Serie A", "La Liga", "MLS"],
    "nationality": "Brazil",
    "positions": ["CAM"],
    "YearOfBirth": 1982,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Kaka_2018.jpg"
  },
  {
    "name": "Rivaldo",
    "clubs": ["Santa Cruz", "Mogi Mirim", "Corinthians (loan)", "Palmeiras", "Deportivo La Coruna", "Barcelona", "AC Milan", "Cruzeiro", "Olympiacos", "AEK Athens", "Bunyodkor", "Sao Paulo", "Kabuscorp", "Sao Caetano Futebol"],
    "leagues": ["Brasileirao", "La Liga", "Serie A", "Greek Super League", "Uzbek Super League", "Girabola", "Brasileirao Serie B"],
    "nationality": "Brazil",
    "positions": ["CAM", "LW"],
    "YearOfBirth": 1972,
    "strongFoot": "Left",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Rivaldo_2014.jpg"
  },
  {
    "name": "Wayne Rooney",
    "clubs": ["Everton", "Manchester United", "DC United", "Derby County"],
    "leagues": ["Premier League", "MLS", "Championship"],
    "nationality": "England",
    "positions": ["ST", "CAM"],
    "YearOfBirth": 1985,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Wayne_Rooney_2018.jpg"
  },
  {
    "name": "Zlatan Ibrahimovic",
    "clubs": ["Malmo FF", "Ajax", "Juventus", "Inter Milan", "Barcelona", "AC Milan", "PSG", "Manchester United", "LA Galaxy"],
    "leagues": ["Allsvenskan", "Eredivisie", "Serie A", "La Liga", "Ligue 1", "Premier League", "MLS"],
    "nationality": "Sweden",
    "positions": ["ST"],
    "YearOfBirth": 1981,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8c/Zlatan_Ibrahimovi%C4%87_2018.jpg"
  },
  {
    "name": "David Villa",
    "clubs": ["Sporting Gijon", "Real Zaragoza", "Valencia", "Barcelona", "Atletico Madrid", "New York City FC", "Melbourne City (loan)", "Vissel Kobe"],
    "leagues": ["La Liga", "MLS", "A-League", "J1 League"],
    "nationality": "Spain",
    "positions": ["ST", "LW"],
    "YearOfBirth": 1981,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3e/David_Villa_2018.jpg"
  },
  {
    "name": "Fernando Torres",
    "clubs": ["Atletico Madrid", "Liverpool", "Chelsea", "AC Milan", "Atletico Madrid", "Sagan Tosu"],
    "leagues": ["La Liga", "Premier League", "Serie A", "J1 League"],
    "nationality": "Spain",
    "positions": ["ST"],
    "YearOfBirth": 1984,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Fernando_Torres_2017.jpg"
  },
  {
    "name": "Sergio Aguero",
    "clubs": ["Independiente", "Atletico Madrid", "Manchester City", "Barcelona"],
    "leagues": ["Argentine Primera División", "La Liga", "Premier League"],
    "nationality": "Argentina",
    "positions": ["ST"],
    "YearOfBirth": 1988,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Sergio_Ag%C3%BCero_2018.jpg"
  },
  {
    "name": "Angel Di Maria",
    "clubs": ["Rosario Central", "Benfica", "Real Madrid", "Manchester United", "PSG", "Juventus", "Benfica"],
    "leagues": ["Argentine Primera División", "Primeira Liga", "La Liga", "Premier League", "Ligue 1", "Serie A"],
    "nationality": "Argentina",
    "positions": ["RW", "LW", "CAM"],
    "YearOfBirth": 1988,
    "strongFoot": "Left",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Angel_Di_Maria_2018.jpg"
  },
  {
    "name": "Mesut Ozil",
    "clubs": ["Schalke", "Werder Bremen", "Real Madrid", "Arsenal", "Fenerbahce", "Istanbul Basaksehir"],
    "leagues": ["Bundesliga", "La Liga", "Premier League", "Turkish Super Lig"],
    "nationality": "Germany",
    "positions": ["CAM"],
    "YearOfBirth": 1988,
    "strongFoot": "Left",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Mesut_%C3%96zil_2018.jpg"
  },
  {
    "name": "Toni Kroos",
    "clubs": ["Bayern Munich", "Bayer Leverkusen (loan)", "Real Madrid"],
    "leagues": ["Bundesliga", "La Liga"],
    "nationality": "Germany",
    "positions": ["CM", "CDM"],
    "YearOfBirth": 1990,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Toni_Kroos_2018.jpg"
  },
  {
    "name": "Marco Reus",
    "clubs": ["Rot Weiss Ahlen", "Borussia Monchengladbach", "Borussia Dortmund", "LA Galaxy"],
    "leagues": ["Bundesliga", "MLS"],
    "nationality": "Germany",
    "positions": ["CAM", "LW", "RW"],
    "YearOfBirth": 1989,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Marco_Reus_2018.jpg"
  },
  {
    "name": "Thomas Muller",
    "clubs": ["Bayern Munich", "Vancouver Whitecaps"],
    "leagues": ["Bundesliga", "MLS"],
    "nationality": "Germany",
    "positions": ["CAM", "RW", "ST"],
    "YearOfBirth": 1989,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8c/Thomas_M%C3%BCller_2018.jpg"
  },
  {
    "name": "Bastian Schweinsteiger",
    "clubs": ["Bayern Munich", "Manchester United", "Chicago Fire"],
    "leagues": ["Bundesliga", "Premier League", "MLS"],
    "nationality": "Germany",
    "positions": ["CM", "CDM"],
    "YearOfBirth": 1984,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Bastian_Schweinsteiger_2018.jpg"
  },
  {
    "name": "Petr Cech",
    "clubs": ["Chmel Blsany", "Sparta Prague", "Rennes", "Chelsea", "Arsenal"],
    "leagues": ["Czech First League", "Ligue 1", "Premier League"],
    "nationality": "Czech Republic",
    "positions": ["GK"],
    "YearOfBirth": 1982,
    "strongFoot": "Left",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/2e/Petr_%C4%8Cech_2018.jpg"
  },
  {
    "name": "Jan Oblak",
    "clubs": ["Olimpija Ljubljana", "Benfica", "Beira-Mar (loan)", "Uniao de Leiria (loan)", "Rio Ave (loan)", "Atletico Madrid"],
    "leagues": ["Slovenian PrvaLiga", "Primeira Liga", "La Liga"],
    "nationality": "Slovenia",
    "positions": ["GK"],
    "YearOfBirth": 1993,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Jan_Oblak_2018.jpg"
  },
  {
    "name": "Thibaut Courtois",
    "clubs": ["Genk", "Chelsea", "Atletico Madrid (loan)", "Real Madrid"],
    "leagues": ["Belgian Pro League", "Premier League", "La Liga"],
    "nationality": "Belgium",
    "positions": ["GK"],
    "YearOfBirth": 1992,
    "strongFoot": "Left",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Thibaut_Courtois_2018.jpg"
  },
  {
    "name": "Marc-Andre ter Stegen",
    "clubs": ["Borussia Monchengladbach", "Barcelona", "Girona (loan)"],
    "leagues": ["Bundesliga", "La Liga", "Serie A"],
    "nationality": "Germany",
    "positions": ["GK"],
    "YearOfBirth": 1992,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Marc-Andr%C3%A9_ter_Stegen_2018.jpg"
  },
  {
    "name": "Jordi Alba",
    "clubs": ["Cornella", "Gimnastic", "Valencia", "Barcelona", "Inter Miami"],
    "leagues": ["La Liga", "Segunda División", "MLS"],
    "nationality": "Spain",
    "positions": ["LB"],
    "YearOfBirth": 1989,
    "strongFoot": "Left",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Jordi_Alba_2018.jpg"
  },
  {
    "name": "Dani Alves",
    "clubs": ["Bahia", "Sevilla", "Barcelona", "Juventus", "PSG", "Sao Paulo", "Barcelona", "UNAM"],
    "leagues": ["Brasileirao", "La Liga", "Serie A", "Ligue 1", "Liga MX"],
    "nationality": "Brazil",
    "positions": ["RB"],
    "YearOfBirth": 1983,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8c/Dani_Alves_2018.jpg"
  },
  {
    "name": "Joao Cancelo",
    "clubs": ["Benfica", "Valencia", "Inter Milan (loan)", "Juventus", "Manchester City", "Bayern Munich (loan)", "Barcelona (loan)", "Al Hilal"],
    "leagues": ["Primeira Liga", "La Liga", "Serie A", "Premier League", "Bundesliga", "Saudi Pro League"],
    "nationality": "Portugal",
    "positions": ["RB", "LB"],
    "YearOfBirth": 1994,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/2e/Jo%C3%A3o_Cancelo_2021.jpg"
  },
  {
    "name": "Kyle Walker",
    "clubs": ["Sheffield United", "Northampton Town (loan)", "Queens Park Rangers (loan)", "Aston Villa (loan)", "Tottenham Hotspur", "Manchester City", "Burnley"],
    "leagues": ["Premier League", "Championship"],
    "nationality": "England",
    "positions": ["RB", "CB"],
    "YearOfBirth": 1990,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Kyle_Walker_2018.jpg"
  },
  {
    "name": "Raphael Varane",
    "clubs": ["Lens", "Real Madrid", "Manchester United", "Como"],
    "leagues": ["Ligue 1", "La Liga", "Premier League", "Serie A"],
    "nationality": "France",
    "positions": ["CB"],
    "YearOfBirth": 1993,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Rapha%C3%ABl_Varane_2018.jpg"
  },
  {
    "name": "Kalidou Koulibaly",
    "clubs": ["Metz", "Genk", "Napoli", "Chelsea", "Al Hilal"],
    "leagues": ["Ligue 2", "Belgian Pro League", "Serie A", "Premier League", "Saudi Pro League"],
    "nationality": "Senegal",
    "positions": ["CB"],
    "YearOfBirth": 1991,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Kalidou_Koulibaly_2018.jpg"
  },
  {
    "name": "Vinicius Junior",
    "clubs": ["Flamengo", "Real Madrid"],
    "leagues": ["Brasileirao", "La Liga"],
    "nationality": "Brazil",
    "positions": ["LW", "RW"],
    "YearOfBirth": 2000,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Vinicius_Junior_2022.jpg"
  },
  {
    "name": "Rodrygo",
    "clubs": ["Santos", "Real Madrid"],
    "leagues": ["Brasileirao", "La Liga"],
    "nationality": "Brazil",
    "positions": ["RW", "LW", "ST"],
    "YearOfBirth": 2001,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Rodrygo_2022.jpg"
  },
  {
    "name": "Jude Bellingham",
    "clubs": ["Birmingham City", "Borussia Dortmund", "Real Madrid"],
    "leagues": ["Championship", "Bundesliga", "La Liga"],
    "nationality": "England",
    "positions": ["CM", "CAM"],
    "YearOfBirth": 2003,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Jude_Bellingham_2022.jpg"
  },
  {
    "name": "Pedri",
    "clubs": ["Las Palmas", "Barcelona"],
    "leagues": ["La Liga"],
    "nationality": "Spain",
    "positions": ["CM", "CAM"],
    "YearOfBirth": 2002,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3f/Pedri_2021.jpg"
  },
  {
    "name": "Gavi",
    "clubs": ["Barcelona"],
    "leagues": ["La Liga"],
    "nationality": "Spain",
    "positions": ["CM", "CAM"],
    "YearOfBirth": 2004,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4d/Gavi_2021.jpg"
  },
  {
    "name": "Frenkie de Jong",
    "clubs": ["Willem II", "Ajax", "Barcelona"],
    "leagues": ["Eredivisie", "La Liga"],
    "nationality": "Netherlands",
    "positions": ["CM", "CDM"],
    "YearOfBirth": 1997,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Frenkie_de_Jong_2022.jpg"
  },
  {
    "name": "Lautaro Martinez",
    "clubs": ["Racing Club", "Inter Milan"],
    "leagues": ["Argentine Primera División", "Serie A"],
    "nationality": "Argentina",
    "positions": ["ST"],
    "YearOfBirth": 1997,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Lautaro_Mart%C3%ADnez_2022.jpg"
  },
  {
    "name": "Rafael Leao",
    "clubs": ["Sporting CP", "Lille", "AC Milan"],
    "leagues": ["Primeira Liga", "Ligue 1", "Serie A"],
    "nationality": "Portugal",
    "positions": ["LW", "ST"],
    "YearOfBirth": 1999,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3f/Rafael_Le%C3%A3o_2022.jpg"
  },
  {
    "name": "Bukayo Saka",
    "clubs": ["Arsenal"],
    "leagues": ["Premier League"],
    "nationality": "England",
    "positions": ["RW", "LW", "LB"],
    "YearOfBirth": 2001,
    "strongFoot": "Left",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Bukayo_Saka_2022.jpg"
  },
  {
    "name": "Declan Rice",
    "clubs": ["West Ham United", "Arsenal"],
    "leagues": ["Premier League"],
    "nationality": "England",
    "positions": ["CDM", "CM"],
    "YearOfBirth": 1999,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Declan_Rice_2021.jpg"
  },
  {
    "name": "Harry Kane",
    "clubs": ["Tottenham Hotspur", "Leyton Orient (loan)", "Millwall (loan)", "Norwich City (loan)", "Leicester City (loan)", "Bayern Munich"],
    "leagues": ["Premier League", "Championship", "Bundesliga"],
    "nationality": "England",
    "positions": ["ST"],
    "YearOfBirth": 1993,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8c/Harry_Kane_2018.jpg"
  },
  {
    "name": "Son Heung-min",
    "clubs": ["Hamburg", "Bayer Leverkusen", "Tottenham Hotspur", "LAFC"],
    "leagues": ["Bundesliga", "Premier League", "MLS"],
    "nationality": "South Korea",
    "positions": ["LW", "RW", "ST"],
    "YearOfBirth": 1992,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Son_Heung-min_2019.jpg"
  },
  {
    "name": "James Maddison",
    "clubs": ["Coventry City", "Aberdeen (loan)", "Norwich City", "Leicester City", "Tottenham Hotspur"],
    "leagues": ["Championship", "Scottish Premiership", "Premier League"],
    "nationality": "England",
    "positions": ["CAM", "CM"],
    "YearOfBirth": 1996,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4b/James_Maddison_2021.jpg"
  },
  {
    "name": "Bruno Fernandes",
    "clubs": ["Novara", "Udinese", "Sampdoria", "Sporting CP", "Manchester United"],
    "leagues": ["Serie A", "Primeira Liga", "Premier League"],
    "nationality": "Portugal",
    "positions": ["CAM", "CM"],
    "YearOfBirth": 1994,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Bruno_Fernandes_2021.jpg"
  },
  {
    "name": "Casemiro",
    "clubs": ["Sao Paulo", "Real Madrid", "Porto (loan)", "Manchester United"],
    "leagues": ["Brasileirao", "La Liga", "Primeira Liga", "Premier League"],
    "nationality": "Brazil",
    "positions": ["CDM", "CM"],
    "YearOfBirth": 1992,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Casemiro_2018.jpg"
  },
  {
    "name": "Marcus Rashford",
    "clubs": ["Manchester United", "Aston Villa (loan)", "Barcelona (loan)"],
    "leagues": ["Premier League", "La Liga"],
    "nationality": "England",
    "positions": ["LW", "ST"],
    "YearOfBirth": 1997,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Marcus_Rashford_2018.jpg"
  },
  {
    "name": "Jadon Sancho",
    "clubs": ["Borussia Dortmund", "Manchester United", "Chelsea (loan)", "Aston Villa (loan)"],
    "leagues": ["Bundesliga", "Premier League"],
    "nationality": "England",
    "positions": ["RW", "LW"],
    "YearOfBirth": 2000,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Jadon_Sancho_2020.jpg"
  },
  {
    "name": "Erik ten Hag",
    "clubs": ["Twente", "De Graafschap", "RKC Waalwijk", "Utrecht"],
    "leagues": ["Eredivisie"],
    "nationality": "Netherlands",
    "positions": ["CB"],
    "YearOfBirth": 1970,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Erik_ten_Hag_2017.jpg"
  },
  {
    "name": "Joao Felix",
    "clubs": ["Benfica", "Atletico Madrid", "Chelsea (loan)", "Barcelona (loan)", "AC Milan (loan)", "Al Nassr"],
    "leagues": ["Primeira Liga", "La Liga", "Premier League", "Serie A", "Saudi Pro League"],
    "nationality": "Portugal",
    "positions": ["CF", "LW", "CAM"],
    "YearOfBirth": 1999,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Jo%C3%A3o_F%C3%A9lix_2021.jpg"
  },
  {
    "name": "Antoine Griezmann",
    "clubs": ["Real Sociedad", "Atletico Madrid", "Barcelona"],
    "leagues": ["La Liga"],
    "nationality": "France",
    "positions": ["ST", "CF", "LW"],
    "YearOfBirth": 1991,
    "strongFoot": "Left",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Antoine_Griezmann_2018.jpg"
  },
  {
    "name": "Karim Adeyemi",
    "clubs": ["Red Bull Salzburg", "Borussia Dortmund"],
    "leagues": ["Austrian Bundesliga", "Bundesliga"],
    "nationality": "Germany",
    "positions": ["RW", "ST", "LW"],
    "YearOfBirth": 2002,
    "strongFoot": "Left",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Karim_Adeyemi_2022.jpg"
  },
  {
    "name": "Jamal Musiala",
    "clubs": ["Bayern Munich"],
    "leagues": ["Bundesliga"],
    "nationality": "Germany",
    "positions": ["CAM", "LW", "CM"],
    "YearOfBirth": 2003,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Jamal_Musiala_2022.jpg"
  },
  {
    "name": "Kai Havertz",
    "clubs": ["Bayer Leverkusen", "Chelsea", "Arsenal"],
    "leagues": ["Bundesliga", "Premier League"],
    "nationality": "Germany",
    "positions": ["CAM", "ST", "CM"],
    "YearOfBirth": 1999,
    "strongFoot": "Left",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Kai_Havertz_2022.jpg"
  },
  {
    "name": "Ilkay Gundogan",
    "clubs": ["VfL Bochum", "Nurnberg", "Borussia Dortmund", "Manchester City", "Barcelona", "Galatasaray"],
    "leagues": ["Bundesliga", "Premier League", "La Liga", "Turkish Super Lig"],
    "nationality": "Germany",
    "positions": ["CM"],
    "YearOfBirth": 1990,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Ilkay_Gundogan_2018.jpg"
  },
  {
    "name": "Rodri",
    "clubs": ["Villarreal", "Atletico Madrid", "Manchester City"],
    "leagues": ["La Liga", "Premier League"],
    "nationality": "Spain",
    "positions": ["CDM", "CM"],
    "YearOfBirth": 1996,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Rodri_2021.jpg"
  },
  {
    "name": "Bernardo Silva",
    "clubs": ["Benfica", "Monaco", "Manchester City"],
    "leagues": ["Primeira Liga", "Ligue 1", "Premier League"],
    "nationality": "Portugal",
    "positions": ["RW", "CAM", "CM"],
    "YearOfBirth": 1994,
    "strongFoot": "Left",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Bernardo_Silva_2018.jpg"
  },
  {
    "name": "Riyad Mahrez",
    "clubs": ["Le Havre", "Leicester City", "Manchester City", "Al Ahli"],
    "leagues": ["Ligue 2", "Premier League", "Saudi Pro League"],
    "nationality": "Algeria",
    "positions": ["RW"],
    "YearOfBirth": 1991,
    "strongFoot": "Left",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Riyad_Mahrez_2018.jpg"
  },
  {
    "name": "Ederson",
    "clubs": ["Ribeirao", "Rio Ave", "Benfica", "Manchester City", "Fenerbahce"],
    "leagues": ["Primeira Liga", "Premier League", "Turkish Super Lig"],
    "nationality": "Brazil",
    "positions": ["GK"],
    "YearOfBirth": 1993,
    "strongFoot": "Left",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Ederson_2018.jpg"
  },
  {
    "name": "Alisson Becker",
    "clubs": ["Internacional", "Roma", "Liverpool"],
    "leagues": ["Brasileirao", "Serie A", "Premier League"],
    "nationality": "Brazil",
    "positions": ["GK"],
    "YearOfBirth": 1992,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Alisson_Becker_2018.jpg"
  },
  {
    "name": "Trent Alexander-Arnold",
    "clubs": ["Liverpool", "Real Madrid"],
    "leagues": ["Premier League", "La Liga"],
    "nationality": "England",
    "positions": ["RB", "CM"],
    "YearOfBirth": 1998,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Trent_Alexander-Arnold_2018.jpg"
  },
  {
    "name": "Ousmane Dembele",
    "clubs": ["Rennes", "Borussia Dortmund", "Barcelona", "PSG"],
    "leagues": ["Ligue 1", "Bundesliga", "La Liga"],
    "nationality": "France",
    "positions": ["RW", "LW"],
    "YearOfBirth": 1997,
    "strongFoot": "Left",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Ousmane_Demb%C3%A9l%C3%A9_2018.jpg"
  },
  {
    "name": "Edinson Cavani",
    "clubs": ["Danubio", "Palermo", "Napoli", "PSG", "Manchester United", "Valencia", "Boca Juniors"],
    "leagues": ["Liga AUF Uruguaya", "Serie A", "Ligue 1", "Premier League", "La Liga", "Argentine Primera División"],
    "nationality": "Uruguay",
    "positions": ["ST"],
    "YearOfBirth": 1987,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Edinson_Cavani_2018.jpg"
  },
  {
    "name": "Paulo Dybala",
    "clubs": ["Instituto", "Palermo", "Juventus", "Roma"],
    "leagues": ["Argentine Primera División", "Serie A"],
    "nationality": "Argentina",
    "positions": ["CF", "CAM", "RW"],
    "YearOfBirth": 1993,
    "strongFoot": "Left",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Paulo_Dybala_2018.jpg"
  },
  {
    "name": "Federico Valverde",
    "clubs": ["Penarol", "Deportivo La Coruna (loan)", "Real Madrid"],
    "leagues": ["Liga AUF Uruguaya", "Segunda División", "La Liga"],
    "nationality": "Uruguay",
    "positions": ["CM", "RW", "CDM", "RB"],
    "YearOfBirth": 1998,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Federico_Valverde_2021.jpg"
  },
  {
    "name": "Achraf Hakimi",
    "clubs": ["Real Madrid", "Borussia Dortmund (loan)", "Inter Milan", "PSG"],
    "leagues": ["La Liga", "Bundesliga", "Serie A", "Ligue 1"],
    "nationality": "Morocco",
    "positions": ["RB", "RWB", "LB"],
    "YearOfBirth": 1998,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Achraf_Hakimi_2022.jpg"
  },
  {
    "name": "Theo Hernandez",
    "clubs": ["Alaves (loan)", "Real Madrid", "Real Sociedad (loan)", "AC Milan", "Al Hilal"],
    "leagues": ["La Liga", "Serie A", "Saudi Pro League"],
    "nationality": "France",
    "positions": ["LB", "LWB"],
    "YearOfBirth": 1997,
    "strongFoot": "Left",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Théo_Hernandez_2022.jpg"
  },
  {
    "name": "Milan Skriniar",
    "clubs": ["Zilina", "Sampdoria", "Inter Milan", "PSG", "Fenerbahce"],
    "leagues": ["Slovak Super Liga", "Serie A", "Ligue 1", "Turkish Super Lig"],
    "nationality": "Slovakia",
    "positions": ["CB"],
    "YearOfBirth": 1995,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Milan_%C5%A0kriniar_2022.jpg"
  },
  {
    "name": "Victor Osimhen",
    "clubs": ["Wolfsburg", "Charleroi", "Lille", "Napoli", "Galatasaray"],
    "leagues": ["Bundesliga", "Belgian Pro League", "Ligue 1", "Serie A", "Turkish Super Lig"],
    "nationality": "Nigeria",
    "positions": ["ST"],
    "YearOfBirth": 1998,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/5e/Victor_Osimhen_2022.jpg"
  },
  {
    "name": "Khvicha Kvaratskhelia",
    "clubs": ["Dinamo Tbilisi", "Rustavi", "Lokomotiv Moscow", "Rubin Kazan", "Dinamo Batumi", "Napoli", "PSG"],
    "leagues": ["Erovnuli Liga", "Russian Premier League", "Serie A", "Ligue 1"],
    "nationality": "Georgia",
    "positions": ["LW"],
    "YearOfBirth": 2001,
    "strongFoot": "Right",
    "status": "Current",
    "image": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Khvicha_Kvaratskhelia_2022.jpg"
  },
  {
    "name": "Ruud Gullit",
    "clubs": ["Haarlem", "Feyenoord", "PSV", "AC Milan", "Sampdoria", "Chelsea"],
    "leagues": ["Eredivisie", "Serie A", "Premier League"],
    "nationality": "Netherlands",
    "positions": ["CAM", "CM", "CF"],
    "YearOfBirth": 1962,
    "strongFoot": "Right",
    "status": "Retired",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Ruud_Gullit_1988.jpg"
  }
]
